#!/usr/bin/env bash
# Slimy.ai branch cleanup – MERGE PREVIEW ONLY
# This script prints suggested merge flows; review before running git commands.
set -euo pipefail
echo "=== Slimy.ai Branch Cleanup – Merge Review Plan (PREVIEW) ==="
echo ""
echo "# Consider merging origin/claude/admin-api-test-spine-01CZgJQhnTYQxFvrP7u14EPa into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 1, behind: 1, category: backend_admin_api)"
echo "#   git fetch origin claude/admin-api-test-spine-01CZgJQhnTYQxFvrP7u14EPa:claude/admin-api-test-spine-01CZgJQhnTYQxFvrP7u14EPa || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/admin-api-test-spine-01CZgJQhnTYQxFvrP7u14EPa"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/admin-api-tests-runnable-01LPLzzM8NTYezcPWnhTMPTQ into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 2, behind: 1, category: backend_admin_api)"
echo "#   git fetch origin claude/admin-api-tests-runnable-01LPLzzM8NTYezcPWnhTMPTQ:claude/admin-api-tests-runnable-01LPLzzM8NTYezcPWnhTMPTQ || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/admin-api-tests-runnable-01LPLzzM8NTYezcPWnhTMPTQ"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/admin-api-type-safety-017d3UtBchDXZnC8gxC59neD into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 1, behind: 6, category: backend_admin_api)"
echo "#   git fetch origin claude/admin-api-type-safety-017d3UtBchDXZnC8gxC59neD:claude/admin-api-type-safety-017d3UtBchDXZnC8gxC59neD || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/admin-api-type-safety-017d3UtBchDXZnC8gxC59neD"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/admin-api-type-safety-01PBcjXgk1nzjP2D4PRKHNDE into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 1, behind: 1, category: backend_admin_api)"
echo "#   git fetch origin claude/admin-api-type-safety-01PBcjXgk1nzjP2D4PRKHNDE:claude/admin-api-type-safety-01PBcjXgk1nzjP2D4PRKHNDE || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/admin-api-type-safety-01PBcjXgk1nzjP2D4PRKHNDE"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/admin-cli-bootstrap-01NgMsWhXq5QMangoDLqHNyL into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 1, behind: 15, category: backend_admin_api)"
echo "#   git fetch origin claude/admin-cli-bootstrap-01NgMsWhXq5QMangoDLqHNyL:claude/admin-cli-bootstrap-01NgMsWhXq5QMangoDLqHNyL || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/admin-cli-bootstrap-01NgMsWhXq5QMangoDLqHNyL"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/admin-cli-bootstrapper-018VtucPsqZjRcquPEr8Hhrg into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 1, behind: 15, category: backend_admin_api)"
echo "#   git fetch origin claude/admin-cli-bootstrapper-018VtucPsqZjRcquPEr8Hhrg:claude/admin-cli-bootstrapper-018VtucPsqZjRcquPEr8Hhrg || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/admin-cli-bootstrapper-018VtucPsqZjRcquPEr8Hhrg"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/audit-logging-rollout-01Gnj1jhHyKXYzPsRMKDjscR into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 1, behind: 1, category: backend_admin_api)"
echo "#   git fetch origin claude/audit-logging-rollout-01Gnj1jhHyKXYzPsRMKDjscR:claude/audit-logging-rollout-01Gnj1jhHyKXYzPsRMKDjscR || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/audit-logging-rollout-01Gnj1jhHyKXYzPsRMKDjscR"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/auth-rbac-implementation-012Meoy8C8cZoPrn2Xbh7VqU into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 1, behind: 15, category: backend_admin_api)"
echo "#   git fetch origin claude/auth-rbac-implementation-012Meoy8C8cZoPrn2Xbh7VqU:claude/auth-rbac-implementation-012Meoy8C8cZoPrn2Xbh7VqU || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/auth-rbac-implementation-012Meoy8C8cZoPrn2Xbh7VqU"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/centralize-audit-logging-01GTepJLqYSSYrz6MG55f2Lv into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 1, behind: 1, category: backend_admin_api)"
echo "#   git fetch origin claude/centralize-audit-logging-01GTepJLqYSSYrz6MG55f2Lv:claude/centralize-audit-logging-01GTepJLqYSSYrz6MG55f2Lv || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/centralize-audit-logging-01GTepJLqYSSYrz6MG55f2Lv"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/cleanup-club-analytics-01Fz4VSQDAZSaMDUVG2CrdvZ into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 1, behind: 1, category: backend_admin_api)"
echo "#   git fetch origin claude/cleanup-club-analytics-01Fz4VSQDAZSaMDUVG2CrdvZ:claude/cleanup-club-analytics-01Fz4VSQDAZSaMDUVG2CrdvZ || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/cleanup-club-analytics-01Fz4VSQDAZSaMDUVG2CrdvZ"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/club-analytics-first-pass-01UsFZRsyE5geSUAaR3JUCw3 into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 1, behind: 15, category: backend_admin_api)"
echo "#   git fetch origin claude/club-analytics-first-pass-01UsFZRsyE5geSUAaR3JUCw3:claude/club-analytics-first-pass-01UsFZRsyE5geSUAaR3JUCw3 || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/club-analytics-first-pass-01UsFZRsyE5geSUAaR3JUCw3"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/club-analytics-v2-01WjM3fVSN6nMS6REsQvF1CA into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 2, behind: 15, category: backend_admin_api)"
echo "#   git fetch origin claude/club-analytics-v2-01WjM3fVSN6nMS6REsQvF1CA:claude/club-analytics-v2-01WjM3fVSN6nMS6REsQvF1CA || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/club-analytics-v2-01WjM3fVSN6nMS6REsQvF1CA"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/discord-oauth-sessions-01YWSWByDSYihbemL6u7H7YH into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 1, behind: 15, category: backend_admin_api)"
echo "#   git fetch origin claude/discord-oauth-sessions-01YWSWByDSYihbemL6u7H7YH:claude/discord-oauth-sessions-01YWSWByDSYihbemL6u7H7YH || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/discord-oauth-sessions-01YWSWByDSYihbemL6u7H7YH"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/event-bus-audit-log-012JqPxkwAAALq2pUP4MjhZ4 into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 1, behind: 15, category: backend_admin_api)"
echo "#   git fetch origin claude/event-bus-audit-log-012JqPxkwAAALq2pUP4MjhZ4:claude/event-bus-audit-log-012JqPxkwAAALq2pUP4MjhZ4 || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/event-bus-audit-log-012JqPxkwAAALq2pUP4MjhZ4"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/fix-club-analytics-stability-01DeLSDv98mJigJ2TztPRLCX into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 1, behind: 6, category: backend_admin_api)"
echo "#   git fetch origin claude/fix-club-analytics-stability-01DeLSDv98mJigJ2TztPRLCX:claude/fix-club-analytics-stability-01DeLSDv98mJigJ2TztPRLCX || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/fix-club-analytics-stability-01DeLSDv98mJigJ2TztPRLCX"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/harden-admin-auth-01YUTbcGvAjBrr2f7ATQFNmF into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 1, behind: 6, category: backend_admin_api)"
echo "#   git fetch origin claude/harden-admin-auth-01YUTbcGvAjBrr2f7ATQFNmF:claude/harden-admin-auth-01YUTbcGvAjBrr2f7ATQFNmF || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/harden-admin-auth-01YUTbcGvAjBrr2f7ATQFNmF"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/map-admin-auth-flow-014qDQP4gGXCjtMLAA8H94ph into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 2, behind: 6, category: backend_admin_api)"
echo "#   git fetch origin claude/map-admin-auth-flow-014qDQP4gGXCjtMLAA8H94ph:claude/map-admin-auth-flow-014qDQP4gGXCjtMLAA8H94ph || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/map-admin-auth-flow-014qDQP4gGXCjtMLAA8H94ph"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/setup-admin-api-server-01NdEijLLznDfRSmK5vUy25K into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 1, behind: 15, category: backend_admin_api)"
echo "#   git fetch origin claude/setup-admin-api-server-01NdEijLLznDfRSmK5vUy25K:claude/setup-admin-api-server-01NdEijLLznDfRSmK5vUy25K || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/setup-admin-api-server-01NdEijLLznDfRSmK5vUy25K"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/standardize-admin-api-errors-01DUML4HqCmpNpynwQqkf9X8 into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 1, behind: 6, category: backend_admin_api)"
echo "#   git fetch origin claude/standardize-admin-api-errors-01DUML4HqCmpNpynwQqkf9X8:claude/standardize-admin-api-errors-01DUML4HqCmpNpynwQqkf9X8 || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/standardize-admin-api-errors-01DUML4HqCmpNpynwQqkf9X8"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/mega-foundation-ready-01WyF9x7yHhAjUSN41oNM2th into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 250, behind: 1, category: core_foundation)"
echo "#   git fetch origin claude/mega-foundation-ready-01WyF9x7yHhAjUSN41oNM2th:claude/mega-foundation-ready-01WyF9x7yHhAjUSN41oNM2th || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/mega-foundation-ready-01WyF9x7yHhAjUSN41oNM2th"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/mega-integration-all-branches-01CDmjCR8yPcfsYxpvGB27DT into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 239, behind: 1, category: core_foundation)"
echo "#   git fetch origin claude/mega-integration-all-branches-01CDmjCR8yPcfsYxpvGB27DT:claude/mega-integration-all-branches-01CDmjCR8yPcfsYxpvGB27DT || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/mega-integration-all-branches-01CDmjCR8yPcfsYxpvGB27DT"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/mega-foundation-working into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 240, behind: 1, category: core_foundation)"
echo "#   git fetch origin mega-foundation-working:mega-foundation-working || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff mega-foundation-working"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/add-e2e-tests-01GScYYvW4EgWg49d6XPLpBZ into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 1, behind: 15, category: testing_infra)"
echo "#   git fetch origin claude/add-e2e-tests-01GScYYvW4EgWg49d6XPLpBZ:claude/add-e2e-tests-01GScYYvW4EgWg49d6XPLpBZ || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/add-e2e-tests-01GScYYvW4EgWg49d6XPLpBZ"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/add-fixture-generator-01QiPcowvcLvijaasuWR2VpQ into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 1, behind: 6, category: testing_infra)"
echo "#   git fetch origin claude/add-fixture-generator-01QiPcowvcLvijaasuWR2VpQ:claude/add-fixture-generator-01QiPcowvcLvijaasuWR2VpQ || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/add-fixture-generator-01QiPcowvcLvijaasuWR2VpQ"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/add-test-fixtures-library-01FpivySN368rau6c1yoeebc into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 1, behind: 6, category: testing_infra)"
echo "#   git fetch origin claude/add-test-fixtures-library-01FpivySN368rau6c1yoeebc:claude/add-test-fixtures-library-01FpivySN368rau6c1yoeebc || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/add-test-fixtures-library-01FpivySN368rau6c1yoeebc"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/e2e-test-stub-config-01WB1sB4badK8hMww1oChJrV into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 1, behind: 6, category: testing_infra)"
echo "#   git fetch origin claude/e2e-test-stub-config-01WB1sB4badK8hMww1oChJrV:claude/e2e-test-stub-config-01WB1sB4badK8hMww1oChJrV || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/e2e-test-stub-config-01WB1sB4badK8hMww1oChJrV"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/setup-full-stack-testing-011fHBiXNa23d8iuZ2mn3U6g into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 1, behind: 15, category: testing_infra)"
echo "#   git fetch origin claude/setup-full-stack-testing-011fHBiXNa23d8iuZ2mn3U6g:claude/setup-full-stack-testing-011fHBiXNa23d8iuZ2mn3U6g || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/setup-full-stack-testing-011fHBiXNa23d8iuZ2mn3U6g"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/add-auto-deploy-script-01JV2MrTuNLEnmLHwYnqhTXG into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 1, behind: 6, category: tools_cli)"
echo "#   git fetch origin claude/add-auto-deploy-script-01JV2MrTuNLEnmLHwYnqhTXG:claude/add-auto-deploy-script-01JV2MrTuNLEnmLHwYnqhTXG || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/add-auto-deploy-script-01JV2MrTuNLEnmLHwYnqhTXG"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/add-deployment-checklist-tool-01LTGSsbDME9Rpdxqm7bU7aG into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 1, behind: 6, category: tools_cli)"
echo "#   git fetch origin claude/add-deployment-checklist-tool-01LTGSsbDME9Rpdxqm7bU7aG:claude/add-deployment-checklist-tool-01LTGSsbDME9Rpdxqm7bU7aG || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/add-deployment-checklist-tool-01LTGSsbDME9Rpdxqm7bU7aG"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/add-health-check-script-01MK52ruEj6Q8j5BHfBo6UMY into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 1, behind: 6, category: tools_cli)"
echo "#   git fetch origin claude/add-health-check-script-01MK52ruEj6Q8j5BHfBo6UMY:claude/add-health-check-script-01MK52ruEj6Q8j5BHfBo6UMY || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/add-health-check-script-01MK52ruEj6Q8j5BHfBo6UMY"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/build-api-client-module-01P4kYYCNHJmDkpLmVo9uXoS into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 1, behind: 15, category: tools_cli)"
echo "#   git fetch origin claude/build-api-client-module-01P4kYYCNHJmDkpLmVo9uXoS:claude/build-api-client-module-01P4kYYCNHJmDkpLmVo9uXoS || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/build-api-client-module-01P4kYYCNHJmDkpLmVo9uXoS"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/cli-health-check-tool-01UjYynfHvHctuYHeVfwPzm1 into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 1, behind: 6, category: tools_cli)"
echo "#   git fetch origin claude/cli-health-check-tool-01UjYynfHvHctuYHeVfwPzm1:claude/cli-health-check-tool-01UjYynfHvHctuYHeVfwPzm1 || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/cli-health-check-tool-01UjYynfHvHctuYHeVfwPzm1"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/cli-local-radar-tool-01CWQLyg5deBi3uc5VQ9LenV into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 1, behind: 1, category: tools_cli)"
echo "#   git fetch origin claude/cli-local-radar-tool-01CWQLyg5deBi3uc5VQ9LenV:claude/cli-local-radar-tool-01CWQLyg5deBi3uc5VQ9LenV || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/cli-local-radar-tool-01CWQLyg5deBi3uc5VQ9LenV"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/create-scripts-index-01CLYM8VeTxj6dbFS7wgxVUr into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 1, behind: 6, category: tools_cli)"
echo "#   git fetch origin claude/create-scripts-index-01CLYM8VeTxj6dbFS7wgxVUr:claude/create-scripts-index-01CLYM8VeTxj6dbFS7wgxVUr || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/create-scripts-index-01CLYM8VeTxj6dbFS7wgxVUr"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/implement-http-client-01Qr4vTRRRzuZT8f5Jq4S6bk into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 2, behind: 1, category: tools_cli)"
echo "#   git fetch origin claude/implement-http-client-01Qr4vTRRRzuZT8f5Jq4S6bk:claude/implement-http-client-01Qr4vTRRRzuZT8f5Jq4S6bk || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/implement-http-client-01Qr4vTRRRzuZT8f5Jq4S6bk"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/organize-npm-scripts-01QhFgUsWbdbU4N2QeXtxYxC into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 1, behind: 6, category: tools_cli)"
echo "#   git fetch origin claude/organize-npm-scripts-01QhFgUsWbdbU4N2QeXtxYxC:claude/organize-npm-scripts-01QhFgUsWbdbU4N2QeXtxYxC || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/organize-npm-scripts-01QhFgUsWbdbU4N2QeXtxYxC"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/snail-tools-ux-flow-01B7hpgQz4f6dVqbwNeMSpMz into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 1, behind: 6, category: tools_cli)"
echo "#   git fetch origin claude/snail-tools-ux-flow-01B7hpgQz4f6dVqbwNeMSpMz:claude/snail-tools-ux-flow-01B7hpgQz4f6dVqbwNeMSpMz || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/snail-tools-ux-flow-01B7hpgQz4f6dVqbwNeMSpMz"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/typed-http-client-01BNjPshnKmZS4ntG8Mmr1ac into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 1, behind: 3, category: tools_cli)"
echo "#   git fetch origin claude/typed-http-client-01BNjPshnKmZS4ntG8Mmr1ac:claude/typed-http-client-01BNjPshnKmZS4ntG8Mmr1ac || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/typed-http-client-01BNjPshnKmZS4ntG8Mmr1ac"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/typed-http-client-01Lnkv3awRwsdCehRA77NQZ9 into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 1, behind: 3, category: tools_cli)"
echo "#   git fetch origin claude/typed-http-client-01Lnkv3awRwsdCehRA77NQZ9:claude/typed-http-client-01Lnkv3awRwsdCehRA77NQZ9 || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/typed-http-client-01Lnkv3awRwsdCehRA77NQZ9"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
echo "# Consider merging origin/claude/typed-http-client-api-01VY9AvVtdNwGzaotTHSr4Sb into claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn (ahead: 1, behind: 1, category: tools_cli)"
echo "#   git fetch origin claude/typed-http-client-api-01VY9AvVtdNwGzaotTHSr4Sb:claude/typed-http-client-api-01VY9AvVtdNwGzaotTHSr4Sb || true"
echo "#   git checkout claude/mega-foundation-dev-01J8TUvHwDPPTo8SSqE5MVbn"
echo "#   git merge --no-ff claude/typed-http-client-api-01VY9AvVtdNwGzaotTHSr4Sb"
echo "#   # Resolve conflicts, run prisma generate + pnpm test suites, then push"
echo ""
