// PM2 ecosystem config for slimy-bot-v2 (monorepo TypeScript bot)
// Generated by bot-monorepo-chunk6-cutover
// Cutover target: atomic switch from /opt/slimy/app (JS) to monorepo TypeScript
//
// NOTE: .env file must exist in cwd (/home/slimy/slimy-monorepo/apps/bot/.env)
// Copy from /opt/slimy/app/.env or symlink: ln -sf /opt/slimy/app/.env .env
module.exports = {
  apps: [
    {
      name: 'slimy-bot-v2',
      cwd: '/home/slimy/slimy-monorepo/apps/bot',
      script: 'node',
      args: 'dist/index.js',
      env: {
        NODE_ENV: 'production',
      },
    },
  ],
};
