// Mock fixtures for Trader UI

import type { Market, FeedStatus, Decision, RiskMetrics, LogEntry } from "./types";

export const mockMarkets: Market[] = [
  {
    id: "1",
    symbol: "BTC/USDT",
    exchange: "binance",
    status: "active",
    lastPrice: 43250.5,
    volume24h: 1250000000,
    change24h: 2.35,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "2",
    symbol: "ETH/USDT",
    exchange: "binance",
    status: "active",
    lastPrice: 2280.75,
    volume24h: 580000000,
    change24h: 1.82,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "3",
    symbol: "SOL/USDT",
    exchange: "binance",
    status: "active",
    lastPrice: 98.42,
    volume24h: 320000000,
    change24h: -0.45,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "4",
    symbol: "BTC/USD",
    exchange: "coinbase",
    status: "active",
    lastPrice: 43265.0,
    volume24h: 890000000,
    change24h: 2.28,
    updatedAt: new Date().toISOString(),
  },
  {
    id: "5",
    symbol: "ARB/USDT",
    exchange: "binance",
    status: "halted",
    lastPrice: 1.24,
    volume24h: 45000000,
    change24h: 0.0,
    updatedAt: new Date(Date.now() - 3600000).toISOString(),
  },
];

export const mockFeeds: FeedStatus[] = [
  {
    id: "1",
    name: "Binance WS",
    connected: true,
    latencyMs: 12,
    messagesPerSec: 450,
    lastMessage: new Date().toISOString(),
  },
  {
    id: "2",
    name: "Coinbase WS",
    connected: true,
    latencyMs: 18,
    messagesPerSec: 280,
    lastMessage: new Date().toISOString(),
  },
  {
    id: "3",
    name: "Kraken WS",
    connected: false,
    latencyMs: 0,
    messagesPerSec: 0,
    lastMessage: new Date(Date.now() - 120000).toISOString(),
  },
  {
    id: "4",
    name: "OKX WS",
    connected: true,
    latencyMs: 25,
    messagesPerSec: 320,
    lastMessage: new Date().toISOString(),
  },
];

export const mockDecisions: Decision[] = [
  {
    id: "d1",
    timestamp: new Date().toISOString(),
    market: "BTC/USDT",
    signal: "long",
    confidence: 0.78,
    edge: "momentum",
    executed: false,
    notes: "Strong momentum confirmation on 4H timeframe",
  },
  {
    id: "d2",
    timestamp: new Date(Date.now() - 300000).toISOString(),
    market: "ETH/USDT",
    signal: "flat",
    confidence: 0.45,
    edge: "mean_reversion",
    executed: false,
    notes: "Conflicting signals, staying neutral",
  },
  {
    id: "d3",
    timestamp: new Date(Date.now() - 900000).toISOString(),
    market: "SOL/USDT",
    signal: "short",
    confidence: 0.65,
    edge: "breakout",
    executed: false,
    notes: "Support level breakdown detected",
  },
  {
    id: "d4",
    timestamp: new Date(Date.now() - 1800000).toISOString(),
    market: "BTC/USD",
    signal: "long",
    confidence: 0.82,
    edge: "momentum",
    executed: false,
  },
  {
    id: "d5",
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    market: "ARB/USDT",
    signal: "flat",
    confidence: 0.33,
    edge: "volatility",
    executed: false,
    notes: "Low confidence, market halted",
  },
];

export const mockRisk: RiskMetrics = {
  totalExposure: 125000,
  maxDrawdown: 0.082,
  sharpeRatio: 1.45,
  positionCount: 3,
  unrealizedPnl: 2340.5,
  dailyPnl: 1250.0,
  weeklyPnl: 4820.0,
};

export const mockLogs: LogEntry[] = [
  {
    id: "l1",
    timestamp: new Date().toISOString(),
    level: "info",
    source: "engine",
    message: "Strategy cycle completed - 5 markets analyzed",
  },
  {
    id: "l2",
    timestamp: new Date(Date.now() - 5000).toISOString(),
    level: "info",
    source: "feed",
    message: "Binance WS reconnected successfully",
  },
  {
    id: "l3",
    timestamp: new Date(Date.now() - 15000).toISOString(),
    level: "warn",
    source: "feed",
    message: "Kraken WS connection lost - retrying in 30s",
  },
  {
    id: "l4",
    timestamp: new Date(Date.now() - 30000).toISOString(),
    level: "info",
    source: "risk",
    message: "Position limits recalculated",
  },
  {
    id: "l5",
    timestamp: new Date(Date.now() - 60000).toISOString(),
    level: "error",
    source: "feed",
    message: "Kraken WS connection timeout after 3 attempts",
  },
  {
    id: "l6",
    timestamp: new Date(Date.now() - 120000).toISOString(),
    level: "info",
    source: "engine",
    message: "New decision generated for BTC/USDT",
  },
  {
    id: "l7",
    timestamp: new Date(Date.now() - 180000).toISOString(),
    level: "info",
    source: "engine",
    message: "Strategy cycle completed - 5 markets analyzed",
  },
  {
    id: "l8",
    timestamp: new Date(Date.now() - 240000).toISOString(),
    level: "warn",
    source: "risk",
    message: "Approaching daily loss limit (75% utilized)",
  },
];
