/**
 * AI Integration Types for Opportunity Radar
 *
 * This module defines contracts for AI-powered features like summarization
 * and plan generation. Since opps-core doesn't exist yet, we define our own
 * domain types here.
 */

// ============================================================================
// Domain Types (to be imported from opps-core when available)
// ============================================================================

export type FreshnessTier = 'breaking' | 'trend_narrative' | 'market_move' | 'slow_batch';
export type RiskLevel = 'low' | 'medium' | 'high';

/**
 * An opportunity from the radar system
 */
export interface Opportunity {
  id: string;
  title: string;
  description: string;
  url?: string;
  domains: string[];
  freshnessTier: FreshnessTier;
  riskLevel: RiskLevel;
  timeCost?: 'low' | 'medium' | 'high';
  tags?: string[];
  discoveredAt: Date;
}

/**
 * An opportunity with scoring information
 */
export interface ScoredOpportunity {
  opportunity: Opportunity;
  score: number;
  reasons: string[];
}

/**
 * A snapshot of the radar at a point in time
 */
export interface RadarSnapshot {
  timestamp: Date;
  opportunities: Opportunity[];
  domains: string[];
  metadata?: {
    sourceCount?: number;
    queryCount?: number;
    [key: string]: any;
  };
}

/**
 * User profile for personalized recommendations
 */
export interface UserProfile {
  userId: string;
  preferences?: {
    favoriteDomains?: string[];
    riskTolerance?: RiskLevel;
    timeAvailability?: 'low' | 'medium' | 'high';
  };
  history?: {
    completedOpportunities?: string[];
    skippedOpportunities?: string[];
  };
}

/**
 * A bucket of opportunities in a weekly plan
 */
export interface PlanBucket {
  name: string;
  description: string;
  opportunities: ScoredOpportunity[];
  commentary?: string;
}

/**
 * A draft weekly plan generated by AI
 */
export interface WeeklyPlanDraft {
  generatedAt: Date;
  horizonDays: number;
  buckets: PlanBucket[];
  summary?: string;
  metadata?: {
    totalOpportunities: number;
    [key: string]: any;
  };
}

// ============================================================================
// AI Provider Types
// ============================================================================

/**
 * Supported LLM providers
 */
export type LLMProvider = 'openai' | 'anthropic' | 'ollama' | 'other';

/**
 * Contract for summarizing radar snapshots
 */
export interface RadarSummarizer {
  /**
   * Generate a summary of a radar snapshot
   * @param snapshot The radar snapshot to summarize
   * @param options Optional configuration
   * @returns A text summary
   */
  summarizeSnapshot(
    snapshot: RadarSnapshot,
    options?: { style?: 'short' | 'detailed' }
  ): Promise<string>;
}

/**
 * Contract for generating weekly plans
 */
export interface PlanGenerator {
  /**
   * Generate a weekly plan from a radar snapshot
   * @param snapshot The current radar snapshot
   * @param profile User profile for personalization
   * @param options Optional configuration
   * @returns A draft weekly plan
   */
  generatePlan(
    snapshot: RadarSnapshot,
    profile: UserProfile,
    options?: { horizonDays?: number }
  ): Promise<WeeklyPlanDraft>;
}
